import type { Metadata } from "next";
import "./globals.css";

import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import HeaderVisibilityContextProvider from "@/context/HeaderContext";

export const metadata: Metadata = {
  title: "Muhammad Affan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-opensans bg-black text-light-gray`}
      >
        <HeaderVisibilityContextProvider>
          <Header />
          {children}
          <Footer />
        </HeaderVisibilityContextProvider>
      </body>
    </html>
  );
}
