import type { Metadata } from "next";
import "./globals.css";

import { Header, Footer, SlidingWindow } from "@/components/layout";
import HeaderVisibilityContextProvider from "@/context/HeaderContext";

export const metadata: Metadata = {
  title: "Muhammad Affan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-opensans bg-black text-light-gray`}
      >
        <SlidingWindow>
          <HeaderVisibilityContextProvider>
            <Header />
            {children}
            <Footer />
          </HeaderVisibilityContextProvider>
        </SlidingWindow>
      </body>
    </html>
  );
}
