import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contact",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="selection:bg-faun selection:text-black">{children}</main>
  );
}
